<?php
    
    $kpb_content_modules['tcm_content_module_primary_content'] = array (
					'key' => 'kpb_field5c63126bc2f03',
					'name' => 'primary-content',
					'label' => 'Primary Content',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'kpb_field5c63126bc2d43',
							'label' => 'Columns',
							'name' => 'columns',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 4,
							'layout' => 'block',
							'button_label' => 'Add Column',
							'sub_fields' => array (
                                array (
                                    'key' => 'kpb_field5ccb6cfa6e1qw',
                                    'label' => 'Content Type',
                                    'name' => 'content_type',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '33.3',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array (
                                        'wysiwyg' => 'Mixed Content (Editor)',
                                        'image' => 'Image',
                                        'video' => 'Video'
                                    ),
                                    'default_value' => array (
                                        0 => 'wysiwyg',
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 1,
                                    'ajax' => 0,
                                    'return_format' => 'value',
                                    'placeholder' => ''
                                ),
                                array (
                                    'key' => 'kpb_field5c63126bc2dc2',
                                    'label' => 'Width',
                                    'name' => 'width',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '33.3',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array (
                                        'auto' => 'Automatic',
                                        1 => '1/12',
                                        2 => '2/12',
                                        3 => '3/12 (Quarter Width)',
                                        4 => '4/12',
                                        5 => '5/12',
                                        6 => '6/12 (Half Width)',
                                        7 => '7/12',
                                        8 => '8/12',
                                        9 => '9/12 (Three Quarter Width)',
                                        10 => '10/12',
                                        11 => '11/12',
                                        12 => '12/12 (Full Width)',
                                    ),
                                    'default_value' => array (
                                        0 => 'auto',
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 1,
                                    'ajax' => 0,
                                    'return_format' => 'value',
                                    'placeholder' => ''
                                ),
                                array (
                                    'key' => 'kpb_field5ccb287aa9359',
                                    'label' => 'Custom Class (Advanced)',
                                    'name' => 'column_class',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array (
                                        'width' => '33.3',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array (
									'key' => 'kpb_field5c63126bc2e82',
									'label' => 'Column Content',
									'name' => 'wysiwyg',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 1,
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'kpb_field5ccb6cfa6e1qw',
                                                'operator' => '==',
                                                'value' => 'wysiwyg',
                                            ),
                                        ),
                                    ),
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
                                array (
                                    'key' => 'kpb_field5cd9968bc57d7',
                                    'label' => 'Video',
                                    'name' => 'video',
                                    'type' => 'oembed',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'kpb_field5ccb6cfa6e1qw',
                                                'operator' => '==',
                                                'value' => 'video',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'width' => '',
                                    'height' => '',
                                ),
                                array (
                                    'key' => 'kpb_field5cd99527cd869',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'kpb_field5ccb6cfa6e1qw',
                                                'operator' => '==',
                                                'value' => 'image',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => 'png,jpg,jpeg,gif,svg',
                                ),
                                array (
                                    'key' => 'kpb_field5ccb346f9ca03',
                                    'label' => 'Add Link To Image?',
                                    'name' => 'image_link',
                                    'type' => 'radio',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'kpb_field5ccb6cfa6e1qw',
                                                'operator' => '==',
                                                'value' => 'image',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array (
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array (
                                        'none' => 'No Link',
                                        'internal' => 'Internal Link',
                                        'external' => 'External Link',
                                    ),
                                    'allow_null' => 0,
                                    'other_choice' => 0,
                                    'save_other_choice' => 0,
                                    'default_value' => 'internal',
                                    'layout' => 'horizontal',
                                    'return_format' => 'value',
                                ),
                                array (
                                    'key' => 'kpb_field5ccb346f9ca72',
                                    'label' => 'Link',
                                    'name' => 'internal_link',
                                    'type' => 'page_link',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'kpb_field5ccb346f9ca03',
                                                'operator' => '==',
                                                'value' => 'internal',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array (
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array (
                                    ),
                                    'taxonomy' => array (
                                    ),
                                    'allow_null' => 0,
                                    'allow_archives' => 1,
                                    'multiple' => 0,
                                ),
                                array (
                                    'key' => 'kpb_field5ccb346f9cae1',
                                    'label' => 'Link',
                                    'name' => 'external_link',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'kpb_field5ccb346f9ca03',
                                                'operator' => '==',
                                                'value' => 'external',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array (
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                ),
                                array (
                                    'key' => 'kpb_field5ccb346f9cb60',
                                    'label' => 'Open in new browser?',
                                    'name' => 'open_new_browser',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array (
                                        array (
                                            array (
                                                'field' => 'kpb_field5ccb346f9ca03',
                                                'operator' => '==',
                                                'value' => 'internal',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array (
                                        'width' => '33.3',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 0,
                                    'ui' => 1,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                                array (
									'key' => 'kpb_field5c6494941bc56',
									'label' => 'Bottom Padding',
									'name' => 'bottom_padding',
									'type' => 'select',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'default'=> 'Default (No Padding)',
										'double' => 'Double',
										'full' => 'Full',
										'half' => 'Half',
										'quarter'=> 'Quarter'
									),
									'default_value' => 'default',
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 1,
									'ajax' => 0,
									'layout' => 'horizontal',
									'return_format' => 'value',
									'placeholder' => ''
								),
								array (
									'key' => 'kpb_field5c6494941bcc9',
									'label' => 'Top Padding',
									'name' => 'top_padding',
                                    'type' => 'select',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'default'=> 'Default (No Padding)',
										'double' => 'Double',
										'full' => 'Full',
										'half' => 'Half',
										'quarter'=> 'Quarter'
									),
									'default_value' => 'default',
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 1,
									'ajax' => 0,
									'layout' => 'horizontal',
									'return_format' => 'value',
									'placeholder' => ''
								)
							),
						),
					),
					'min' => '',
					'max' => '',
				);
    
?>
